# Solana RPC URL
rpc_url = "https://api.mainnet-beta.solana.com"

# 要自动检测的交易哈希列表 (可选，如果为空则不会自动检测)
auto_detect_hashes = []



# Default log level ("debug", "info",)
log_level = "info"

# MEV检测配置参数
[mev_detection]
# 交易相似度阈值 (0.0-1.0，默认0.5表示50%以上相似度认为是同一个池子)
similarity_threshold = 0.5

# 小额转账阈值 (lamports，默认1,000,000 = 0.001 SOL)
small_transfer_threshold = 1000000

# 价格影响分析法参数
[mev_detection.price_impact]
# 价格影响比例系数 (默认0.01)
price_impact_ratio = 0.01
# 最大损失百分比限制 (默认10.0%)
max_loss_percentage = 10.0

# Token余额变化分析法参数
[mev_detection.token_balance]
# 损失系数 (默认0.005)
loss_coefficient = 0.005
# 最大损失百分比限制 (默认5.0%)
max_loss_percentage = 5.0

# 滑点估算法参数
[mev_detection.slippage]
# 基础滑点 (默认0.001 = 0.1%)
base_slippage = 0.001
# 复杂度因子调整参数 (默认0.2)
complexity_factor = 0.2
# 指令因子调整参数 (默认0.1)
instruction_factor = 0.1
# 最大损失百分比限制 (默认3.0%)
max_loss_percentage = 3.0

# SOL余额变化分析法参数
[mev_detection.sol_balance]
# 影响因子 (默认0.6，即60%的影响因子)
impact_factor = 0.6
# 保守估算比例 (默认0.3，即30%)
conservative_ratio = 0.3
# 最大损失百分比限制 (默认8.0%)
max_loss_percentage = 8.0

# 交易规模估算参数
[mev_detection.trade_size]
# swap交易最少账户数量 (默认6)
min_swap_accounts = 6
# 每个指令的复杂度估算值 (lamports，默认100,000,000 = 0.1 SOL)
instruction_complexity_value = 100000000
# 每个账户的估算值 (lamports，默认50,000,000 = 0.05 SOL)
account_factor_value = 50000000
# 最小交易规模估算 (lamports，默认100,000,000 = 0.1 SOL)
min_trade_size = 100000000
