# Solana RPC URL 建议使用helis rpc
rpc_url = "https://mainnet.helius-rpc.com/?api-key=4c370af7-15b6-4f48-8506-6fdb1a75bd8b"

# Language setting: "en" for English, "zh" for Chinese
language = "zh"

# 要自动检测的交易哈希列表 (可选，如果为空则不会自动检测)
auto_detect_hashes = []

# Default log level ("debug", "info",)
log_level = "info"

# MEV检测配置参数
[mev_detection]
# 交易相似度阈值 (0.0-1.0，默认0.5表示50%以上相似度认为是同一个池子)
similarity_threshold = 0.5

# 小额转账阈值 (lamports，默认1,000,000 = 0.001 SOL)
small_transfer_threshold = 1000000

# 忽略Jito功能 (默认false) - 开启后不查询Jito API，不检查Jito小费，直接基于账户重合分析MEV
# 通用查询方式，适用于验证者/leader作恶的场景，此时交易不在Jito束包中且没有Jito小费
ignore_jito = false

